server:
  port: 8090

app:
  name: payment-ms
  realm: yo-sales
  client-id: payment-ms
  client-secret: JfSiRh5NykLVHdnXUJKADguO3Uz73s4X
  kc-host: https://login-int.yogym.co

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://54.38.35.221:5432/empire?currentSchema=payment_management
    username: admin
    password: eV03^a&T2W2E9r4xG0a^L&Yfc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: payment-ms
            client-secret: JfSiRh5NykLVHdnXUJKADguO3Uz73s4X
            authorization-grant-type: password
        provider:
          keycloak:
            token-uri: https://login-int.yogym.co/realms/yo-sales/protocol/openid-connect/token
            authorization-uri: https://login-int.yogym.co/realms/yo-sales/protocol/openid-connect/auth
            user-info-uri: https://login-int.yogym.co/realms/yo-sales/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: https://login-int.yogym.co/realms/yo-sales/protocol/openid-connect/certs
          issuer-uri: https://login-int.yogym.co/realms/yo-sales

jwt:
  auth:
    converter:
      resource-id: payment-ms
      principle-attribute: preferred_username


cors:
  allowedOrigin: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  allowedCredentials: false
  corsConfiguration: '/**'


feign:
  documentManagement:
    uri: http://54.38.35.221:8087
  notification:
    uri: http://localhost:8086
  yosales:
    uri: http://localhost:8071
    # application.yml


payment:
  webhook-url: https://postpuberty-trigonometric-bev.ngrok-free.dev
  stripe:
    mode: sandbox

  paypal:
    mode: sandbox

  konnect:
    baseUrl: https://api.sandbox.konnect.network/api/v2

  flouci:
    baseUrl: https://developers.flouci.com/api/v2


#logging:
#  level:
#    org:
#      springframework:
#        kafka: DEBUG
#      apache:
#        kafka:
#          clients:
#            producer: DEBUG
